include name of failed container

diff --git a/ecs-deploy b/ecs-deploy
--- a/ecs-deploy
+++ b/ecs-deploy
@@ -570,16 +570,18 @@ function runTask {
         TASK_JSON=$($AWS_ECS describe-tasks --cluster "$CLUSTER"  --tasks "$TASK_ARN")
 
         TASK_STATUS=$(echo $TASK_JSON | jq -r  '.tasks[0].lastStatus')
-        # read newline separated exit codes into TASK_EXIT_CODES array
-        readarray -t TASK_EXIT_CODES < <(echo $TASK_JSON | jq -r  '.tasks[0].containers[].exitCode')
+        # readarray -t reads lines into array. jq -c compacts each array element to one line
+        readarray -t CONTAINERS < <(echo $TASK_JSON | jq -rc '.tasks[0].containers[]')
 
         if [ $TASK_STATUS == "STOPPED" ]; then
             echo "Task finished with status: $TASK_STATUS"
-            for TASK_EXIT_CODE in "${TASK_EXIT_CODES[@]}"; do
-              if [ $TASK_EXIT_CODE != 0 ]; then
-                  echo "Task execution failed with exit code: $TASK_EXIT_CODE"
-                  exit 1
-              fi
+            for CONTAINER in "${CONTAINERS[@]}"; do
+                NAME=$(echo $CONTAINER | jq .name)
+                EXIT_CODE=$(echo $CONTAINER | jq .exitCode)
+                if [ $EXIT_CODE != 0 ]; then
+                    echo "Task execution failed in container $NAME with exit code: $EXIT_CODE"
+                    exit 1
+                fi
             done
             RUN_TASK_SUCCESS=true
             break;
